import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import process from 'node:process';
import { setTimeout as delay } from 'node:timers/promises';
import solc from 'solc';
import {
  http,
  type Abi,
  type Address,
  type Chain,
  createPublicClient,
  createWalletClient,
  encodeAbiParameters,
} from 'viem';
import { mnemonicToAccount } from 'viem/accounts';

// Use the common local-dev phrase, but avoid naming that trips secret scanners.
const ANVIL_TEST_PHRASE = 'test test test test test test test test test test test junk';
const CHAIN_ID = 31337;
const CONTEXT_DIR = path.join(process.cwd(), '.context');
const CONTEXT_FILE = path.join(CONTEXT_DIR, 'e2e-local.json');
const GENERATED_ENV_LOCAL_HEADER = '# generated by bun run e2e:local\n';

async function getFreePort(): Promise<number> {
  return await new Promise((resolve, reject) => {
    const server = net.createServer();
    server.on('error', reject);
    server.listen(0, () => {
      const address = server.address();
      if (!address || typeof address === 'string') {
        server.close(() => reject(new Error('Failed to allocate a free TCP port')));
        return;
      }
      const port = address.port;
      server.close(() => resolve(port));
    });
  });
}

async function tryListen(port: number): Promise<boolean> {
  return await new Promise((resolve) => {
    const server = net.createServer();
    server.once('error', () => resolve(false));
    server.listen(port, '127.0.0.1', () => {
      server.close(() => resolve(true));
    });
  });
}

async function pickPort(): Promise<{ port: number; reason: 'preferred' | 'fallback' }> {
  const preferred = process.env.E2E_LOCAL_PORT ? Number(process.env.E2E_LOCAL_PORT) : 8545;
  const allowFallback = process.env.E2E_LOCAL_ALLOW_FALLBACK_PORT === '1';
  if (Number.isFinite(preferred) && preferred > 0 && preferred < 65536) {
    const ok = await tryListen(preferred);
    if (ok) return { port: preferred, reason: 'preferred' };

    if (!allowFallback) {
      throw new Error(
        `Port ${preferred} is not available. Stop the process using it, or set E2E_LOCAL_ALLOW_FALLBACK_PORT=1 to pick a random free port.`,
      );
    }
  }
  return { port: await getFreePort(), reason: 'fallback' };
}

function compileContracts(): {
  governorAbi: Abi;
  governorBytecode: `0x${string}`;
  targetAbi: Abi;
  targetBytecode: `0x${string}`;
} {
  const source = `
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

contract MockGovernor {
  uint256 public lastProposalId;
  mapping(uint256 => bool) public executed;
  mapping(uint256 => address[]) internal _targets;
  mapping(uint256 => uint256[]) internal _values;
  mapping(uint256 => bytes[]) internal _calldatas;

  event ProposalCreated(uint256 id);
  event ProposalExecuted(uint256 id);

  function propose(
    address[] calldata targets,
    uint256[] calldata values,
    string[] calldata signatures,
    bytes[] calldata calldatas,
    string calldata
  ) external returns (uint256) {
    require(
      targets.length == values.length &&
        targets.length == signatures.length &&
        targets.length == calldatas.length,
      "length mismatch"
    );
    lastProposalId++;
    emit ProposalCreated(lastProposalId);

    for (uint256 i = 0; i < targets.length; i++) {
      bytes memory callData = bytes(signatures[i]).length == 0
        ? calldatas[i]
        : abi.encodePacked(bytes4(keccak256(bytes(signatures[i]))), calldatas[i]);
      _targets[lastProposalId].push(targets[i]);
      _values[lastProposalId].push(values[i]);
      _calldatas[lastProposalId].push(callData);
    }

    return lastProposalId;
  }

  function execute(uint256 proposalId) external payable {
    require(!executed[proposalId], "already executed");
    executed[proposalId] = true;
    address[] storage targets = _targets[proposalId];
    uint256[] storage values = _values[proposalId];
    bytes[] storage calldatas = _calldatas[proposalId];
    for (uint256 i = 0; i < targets.length; i++) {
      (bool ok, ) = targets[i].call{ value: values[i] }(calldatas[i]);
      require(ok, "call failed");
    }
    emit ProposalExecuted(proposalId);
  }
}

contract MockTarget {
  uint256 public value;
  function setValue(uint256 next) external { value = next; }
}
`;

  const input = {
    language: 'Solidity',
    sources: { 'MockGovernor.sol': { content: source } },
    settings: {
      optimizer: { enabled: true, runs: 200 },
      outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
    },
  };

  const output = JSON.parse(solc.compile(JSON.stringify(input)));
  const errors: Array<{ severity?: string; formattedMessage?: string }> = output.errors ?? [];
  const fatal = errors.filter((e) => e.severity === 'error');
  if (fatal.length > 0) {
    throw new Error(fatal.map((e) => e.formattedMessage).join('\n'));
  }

  const contracts = output.contracts['MockGovernor.sol'];
  const compiledGovernor = contracts?.MockGovernor;
  const compiledTarget = contracts?.MockTarget;
  if (!compiledGovernor?.evm?.bytecode?.object) throw new Error('Failed to compile MockGovernor');
  if (!compiledTarget?.evm?.bytecode?.object) throw new Error('Failed to compile MockTarget');
  return {
    governorAbi: compiledGovernor.abi as Abi,
    governorBytecode: `0x${compiledGovernor.evm.bytecode.object}`,
    targetAbi: compiledTarget.abi as Abi,
    targetBytecode: `0x${compiledTarget.evm.bytecode.object}`,
  };
}

function writeSimulationResults({
  governorAddress,
  targetAddress,
  proposer,
  rpcUrl,
  blockNumber,
  timestamp,
  simulationType,
  proposalId,
}: {
  governorAddress: Address;
  targetAddress: Address;
  proposer: Address;
  rpcUrl: string;
  blockNumber: string;
  timestamp: string;
  simulationType: 'new' | 'proposed' | 'executed';
  proposalId: string;
}) {
  const simulationResultsPath = path.join(
    process.cwd(),
    'frontend',
    'public',
    'simulation-results.json',
  );

  const demoValue = 42n;
  const encodedArgs = encodeAbiParameters([{ type: 'uint256' }], [demoValue]);
  const description = `Local e2e smoke: propose setValue(${demoValue}), then flip to proposed to test Execute.`;
  const result = [
    {
      proposalData: {
        id: 'local-e2e',
        targets: [targetAddress],
        values: ['0'],
        signatures: ['setValue(uint256)'],
        calldatas: [encodedArgs],
        description,
      },
      report: {
        status: 'success',
        summary: 'Local e2e smoke',
        markdownReport: '',
        structuredReport: {
          title: 'Local E2E Smoke',
          proposalText: description,
          status: 'success',
          summary: 'Local E2E smoke report (mock governor).',
          checks: [],
          stateChanges: [],
          events: [],
          metadata: {
            proposalId,
            proposer,
            governorAddress,
            chainId: CHAIN_ID,
            chainName: 'Anvil',
            blockExplorerBaseUrl: rpcUrl,
            simulationBlockNumber: blockNumber,
            simulationTimestamp: timestamp,
            simulationType,
          },
        },
      },
    },
  ];

  fs.mkdirSync(path.dirname(simulationResultsPath), { recursive: true });
  fs.writeFileSync(simulationResultsPath, JSON.stringify(result, null, 2));
}

async function main() {
  const { port, reason } = await pickPort();
  const rpcUrl = `http://127.0.0.1:${port}`;
  const frontendDir = path.join(process.cwd(), 'frontend');
  const frontendEnvLocalPath = path.join(frontendDir, '.env.local');
  const envLocalBackupPath = path.join(CONTEXT_DIR, 'frontend.env.local.backup');
  let shouldRestoreEnvLocal = false;

  const anvil = Bun.spawn({
    cmd: [
      'anvil',
      '--silent',
      '--allow-origin',
      '*',
      '--port',
      String(port),
      '--chain-id',
      String(CHAIN_ID),
      '--mnemonic',
      ANVIL_TEST_PHRASE,
    ],
    stdout: 'inherit',
    stderr: 'inherit',
  });

  const chain: Chain = {
    id: CHAIN_ID,
    name: 'Anvil',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: [rpcUrl] }, public: { http: [rpcUrl] } },
    testnet: true,
  };

  const account = mnemonicToAccount(ANVIL_TEST_PHRASE);
  const transport = http(rpcUrl);
  const publicClient = createPublicClient({ chain, transport });
  const walletClient = createWalletClient({ chain, transport, account });

  try {
    for (let i = 0; i < 80; i++) {
      try {
        await publicClient.getBlockNumber();
        break;
      } catch {
        await delay(50);
      }
    }

    const { governorAbi, governorBytecode, targetAbi, targetBytecode } = compileContracts();
    const deployGovernorHash = await walletClient.deployContract({
      abi: governorAbi,
      bytecode: governorBytecode,
      args: [],
    });
    const deployGovernorReceipt = await publicClient.waitForTransactionReceipt({
      hash: deployGovernorHash,
    });
    if (!deployGovernorReceipt.contractAddress) throw new Error('MockGovernor deployment failed');
    const governorAddress = deployGovernorReceipt.contractAddress as Address;

    const deployTargetHash = await walletClient.deployContract({
      abi: targetAbi,
      bytecode: targetBytecode,
      args: [],
    });
    const deployTargetReceipt = await publicClient.waitForTransactionReceipt({
      hash: deployTargetHash,
    });
    if (!deployTargetReceipt.contractAddress) throw new Error('MockTarget deployment failed');
    const targetAddress = deployTargetReceipt.contractAddress as Address;

    const blockNumber = (await publicClient.getBlockNumber()).toString();
    const timestamp = String(Math.floor(Date.now() / 1000));

    fs.mkdirSync(CONTEXT_DIR, { recursive: true });
    fs.writeFileSync(
      CONTEXT_FILE,
      JSON.stringify(
        {
          rpcUrl,
          chainId: CHAIN_ID,
          governorAddress,
          proposerAddress: account.address,
        },
        null,
        2,
      ),
    );

    writeSimulationResults({
      governorAddress,
      targetAddress,
      proposer: account.address,
      rpcUrl,
      blockNumber,
      timestamp,
      simulationType: 'new',
      proposalId: '0',
    });

    console.log('');
    console.log('Local e2e environment is ready:');
    console.log(`- RPC: ${rpcUrl}`);
    if (reason === 'fallback') {
      console.log(
        '- Note: default port 8545 was unavailable; using a random free port (set E2E_LOCAL_PORT=8545 to force).',
      );
    }
    console.log(`- Chain ID: ${CHAIN_ID}`);
    console.log(`- MockGovernor: ${governorAddress}`);
    console.log(`- MockTarget: ${targetAddress}`);
    console.log('');
    console.log('Next steps:');
    console.log('1) Open http://localhost:3000/action');
    console.log('2) In MetaMask: add Localhost 31337 (RPC above), then connect wallet');
    console.log('3) Click "Propose" and confirm the tx');
    console.log('4) Run: bun run e2e:local:set-proposed   (in another terminal)');
    console.log('5) Reload /action, then click "Execute"');
    console.log('');

    if (!process.env.NEXT_PUBLIC_PROJECT_ID) {
      console.log(
        'Note: NEXT_PUBLIC_PROJECT_ID is not set, so WalletConnect options may not appear in RainbowKit.',
      );
      console.log(
        '      To enable WalletConnect, run: NEXT_PUBLIC_PROJECT_ID=... bun run e2e:local',
      );
      console.log('');
    }

    // Conductor-style workspaces sometimes symlink `.env.local` to a protected location.
    // Next.js tries to read it on boot; if it's unreadable we temporarily replace it.
    if (fs.existsSync(frontendEnvLocalPath)) {
      try {
        fs.accessSync(frontendEnvLocalPath, fs.constants.R_OK);
      } catch {
        fs.mkdirSync(CONTEXT_DIR, { recursive: true });
        try {
          const stat = fs.lstatSync(frontendEnvLocalPath);
          if (stat.isSymbolicLink()) {
            const target = fs.readlinkSync(frontendEnvLocalPath);
            fs.writeFileSync(
              path.join(CONTEXT_DIR, 'frontend.env.local.symlink-target.txt'),
              target,
            );
          }
        } catch {
          // best-effort only
        }

        try {
          fs.renameSync(frontendEnvLocalPath, envLocalBackupPath);
        } catch {
          // If rename fails (e.g. cross-device), fall back to unlink.
          fs.unlinkSync(frontendEnvLocalPath);
        }

        fs.writeFileSync(frontendEnvLocalPath, GENERATED_ENV_LOCAL_HEADER);
        shouldRestoreEnvLocal = true;
        console.log(
          `Replaced unreadable ${frontendEnvLocalPath} (backup in ${envLocalBackupPath})`,
        );
      }
    }

    const nextBin = path.join(
      frontendDir,
      'node_modules',
      '.bin',
      process.platform === 'win32' ? 'next.cmd' : 'next',
    );
    if (!fs.existsSync(nextBin)) {
      console.log('Installing frontend dependencies (missing next)...');
      const install = Bun.spawn({
        cmd: ['bun', 'install'],
        cwd: frontendDir,
        stdout: 'inherit',
        stderr: 'inherit',
        env: process.env,
      });
      const code = await install.exited;
      if (code !== 0) throw new Error(`frontend bun install failed (exit ${code})`);
    }

    const frontend = Bun.spawn({
      cmd: ['bun', 'run', 'dev'],
      cwd: frontendDir,
      stdout: 'inherit',
      stderr: 'inherit',
      env: {
        ...process.env,
        NEXT_PUBLIC_CHAIN_ID: String(CHAIN_ID),
        NEXT_PUBLIC_RPC_URL: rpcUrl,
        NEXT_PUBLIC_GOVERNOR_ADDRESS: governorAddress,
      },
    });

    const shutdown = async () => {
      frontend.kill();
      anvil.kill();
      await Promise.allSettled([frontend.exited, anvil.exited]);

      if (shouldRestoreEnvLocal && fs.existsSync(envLocalBackupPath)) {
        try {
          const current = fs.readFileSync(frontendEnvLocalPath, 'utf8');
          if (current.startsWith(GENERATED_ENV_LOCAL_HEADER)) {
            fs.unlinkSync(frontendEnvLocalPath);
            fs.renameSync(envLocalBackupPath, frontendEnvLocalPath);
          }
        } catch {
          // best-effort restore
        }
      }

      process.exit(0);
    };

    process.on('SIGINT', shutdown);
    process.on('SIGTERM', shutdown);

    await Promise.race([frontend.exited, anvil.exited]);
    await shutdown();
  } catch (err) {
    anvil.kill();
    await anvil.exited;
    throw err;
  }
}

await main();
